// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecoverIQ.Api.Data;

#nullable disable

namespace RecoverIQ.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910181905_AddDrillEntities")]
    partial class AddDrillEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("RecoverIQ.Api.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Premise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RunbookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("RunbookId");

                    b.ToTable("Drills");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.DrillResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillStepId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrillStepId")
                        .IsUnique();

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("DrillResponses");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.DrillStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DrillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DrillId");

                    b.ToTable("DrillSteps");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.Runbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("RpoMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RtoMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Runbooks");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.RunbookStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunbookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunbookId");

                    b.ToTable("RunbookSteps");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.Drill", b =>
                {
                    b.HasOne("RecoverIQ.Api.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecoverIQ.Api.Models.Runbook", "Runbook")
                        .WithMany()
                        .HasForeignKey("RunbookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("Runbook");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.DrillResponse", b =>
                {
                    b.HasOne("RecoverIQ.Api.Models.DrillStep", "DrillStep")
                        .WithOne("Response")
                        .HasForeignKey("RecoverIQ.Api.Models.DrillResponse", "DrillStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecoverIQ.Api.Models.User", "SubmittedByUser")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DrillStep");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.DrillStep", b =>
                {
                    b.HasOne("RecoverIQ.Api.Models.Drill", "Drill")
                        .WithMany("Steps")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.Runbook", b =>
                {
                    b.HasOne("RecoverIQ.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.RunbookStep", b =>
                {
                    b.HasOne("RecoverIQ.Api.Models.Runbook", "Runbook")
                        .WithMany("Steps")
                        .HasForeignKey("RunbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runbook");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.Drill", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.DrillStep", b =>
                {
                    b.Navigation("Response");
                });

            modelBuilder.Entity("RecoverIQ.Api.Models.Runbook", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
